import { createRouter,createWebHistory } from "vue-router";
export default createRouter({
    history:createWebHistory(),
    routes:[
        {
            path:'/home',
            component:()=>import('@/page/home/index.vue')
        },
        {
            path:'/hospital',
            component:()=>import('@/page/hospital/index.vue'),
            children:[
                {
                    path:'register',
                    component:()=>import('@/page/hospital/register/index.vue')
                },
                {
                    path:'detail',
                    component:()=>import('@/page/hospital/detail/index.vue')
                },
                {
                    path:'notice',
                    component:()=>import('@/page/hospital/notice/index.vue')
                },
                {
                    path:'close',
                    component:()=>import('@/page/hospital/close/index.vue')
                },
                {
                    path:'search',
                    component:()=>import('@/page/hospital/search/index.vue')
                }
            ]
        },
        {
            path:'/',
            redirect:'/home'
        }

    ],
    scrollBehavior(){
        return{
            left:0,
            top:0
        }
    }
})